server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
  redis:
    cluster:
      nodes: localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005
    timeout: 6000ms
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.apabi.flow.book.model